from django.urls import path
from . import views

urlpatterns = [
    path('admin/', views.admin_home, name='admin_home'),
    path('admin-home/', views.admin_home, name='admin_home'),
    path('add-product/', views.add_product, name='add_product'),
    path('edit-product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete-product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('orders/', views.view_all_orders, name='view_all_orders'),
    path('', views.home, name='home'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('verify-otp/', views.verify_otp, name='verify_otp'),
    path('reset-password/', views.reset_password, name='reset_password'),
    path('logout/', views.logout_view, name='logout'),
    path('order/detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('user/orders/', views.user_orders, name='user_orders'),
    path('product/<int:product_id>/add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('cart/remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('update-cart/<int:product_id>/', views.update_cart, name='update_cart'),
    path('buy-now/<int:product_id>/', views.buy_now, name='buy_now'),
    path('buy_all/', views.buy_all, name='buy_all'),
    path('order/summary/', views.order_summary, name='order_summary'),
    path('order/<int:product_id>/', views.order_product, name='order_product'),
    path('choose-billing-address/', views.choose_billing_address, name='choose_billing_address'),
    path('choose-billing-address/<int:product_id>/', views.choose_billing_address, name='choose_billing_address_with_product'),
    path('finalize-order/<int:product_id>/', views.finalize_order_product, name='finalize_order_product'),
    path('order/detail/<int:order_id>/', views.order_detail, name='order_detail'),
    path('start_payment/<int:product_id>/', views.start_payment, name='start_payment'),
    path('payment_success/', views.payment_success, name='payment_success'),
    path('choose-billing-address/<int:product_id>/', views.choose_billing_address, name='choose_billing_address'),
    
]